#!/usr/bin/env python3
# Template auto-generated by polygraphy [v0.31.0] on 01/01/20 at 10:10:10
# Generation Command: polygraphy run --gen - model.onnx --trt --onnxrt
# This script compares model.onnx between TensorRT and ONNX-Runtime

from polygraphy.logger import G_LOGGER

from polygraphy.backend.onnxrt import OnnxrtRunner, SessionFromOnnx
from polygraphy.backend.trt import EngineFromNetwork, NetworkFromOnnxPath, TrtRunner, CreateConfig
from polygraphy.comparator import Comparator
import sys

# Loaders
parse_network_from_onnx = NetworkFromOnnxPath('model.onnx')
build_engine = EngineFromNetwork(parse_network_from_onnx, config=CreateConfig(fp16=True))
build_onnxrt_session = SessionFromOnnx('model.onnx')

# Runners
runners = [
    TrtRunner(build_engine),
    OnnxrtRunner(build_onnxrt_session),
]

# Runner Execution
results = Comparator.run(runners)

success = True
# Accuracy Comparison
success &= bool(Comparator.compare_accuracy(results))

# Report Results
cmd_run = ' '.join(sys.argv)
if not success:
    G_LOGGER.critical(f"FAILED | Command: {cmd_run}")
G_LOGGER.finish(f"PASSED | Command: {cmd_run}")